# Generated by Django 5.0.6 on 2024-05-10 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="data_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
